export * from './company.interface'
export * from './project.interface'
export * from './user.interface'
export * from './task.interface'
export * from './subTask.interface'
export * from './modalType.interface'
export * from './incidenceModalType.interface'
export * from './todo.interface'